- name: Stop Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group_name: myResourceGroup21
    vm_name: myVM21
  tasks:
    - name: Stop virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        allocated: no
