- hosts: localhost
  connection: local
  vars: 
    resource_group: base-rg
    webapp_name: base-webapp
    plan_name: base-sp
    location: eastus
  tasks:
    - name: creating a resource group "{{ resource_group }}"
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
    - name: creating App service "{{ webapp_name }}" on linux with java Runtime
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ plan_name }}"
          is_linux: true
          sku: s1
          number_of_workers: 1
        frameworks:
          - name: "java"
            version: "8"
            settings:
              java_container: tomcat
              java_container_version: 8.5

