- hosts: localhost
  connection: local
  vars:
    resource_group_webapp: base-rg-web
      #resource_group: base-rg
    webapp_name: base-linuxapp-nani
    plan_name: base-plan
    location: eastus
    traffic_manager_profile_name: base-managerprofile
    traffic_manager_endpoint_name: base-managerendpoint
  tasks:
    - name: creating webapp resource group "{{ resource_group }}"
      azure_rm_resourcegroup:
        name: "{{ resource_group_webapp }}"
        location: "{{ location }}"
          #- name: creating resource group  "{{ resource_group }}"
          #azure_rm_resourcegroup:
          #name: "{{ resource_group }}"
          #location: "{{ location }}"
          #- name: create app service plan  "{{ plan_name }}"
          #azure_rm_appserviceplan:
          # resource_group: "{{ resource_group }}"
          # name: "{{ plan_name }}"
          #location: "{{ location }}"
          #is_linux: true
          #sku: s1
          #umber_of_workers: 1
    - name: create app service on linux with java runtime
      azure_rm_webapp:
        resource_group: "{{ resource_group_webapp }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group_webapp }}"
          name: "{{ plan_name }}"
          is_linux: true
          sku: s1
          number_of_workers: 1
        app_settings:
          testkey: "testvalue"
        frameworks:
          - name: java
            version: 8
            settings:
              java_container: "Tomcat"
              java_container_version: "8.5"
    - name: Get web app facts
      azure_rm_webapp_info:
        resource_group: "{{ resource_group_webapp }}"
        name: "{{ webapp_name }}"
      register: webapp

    - name: Create Traffic Manager Profile
      azure_rm_trafficmanagerprofile:
        resource_group: "{{ resource_group_webapp }}"
        name: "{{ traffic_manager_profile_name }}"
        location: global
        routing_method: performance
        dns_config:
          relative_name: "{{ traffic_manager_profile_name }}"
          ttl:  60
        monitor_config:
          protocol: HTTPS
          port: 80
          path: '/'
    - name: Add endpoint to traffic manager profile, using created web site
      azure_rm_trafficmanagerendpoint:
        resource_group: "{{ resource_group_webapp }}"
        profile_name: "{{ traffic_manager_profile_name }}"
        name: "{{ traffic_manager_endpoint_name }}"
        type: azure_endpoints
        location: "{{ location }}"
        target_resource_id: "{{ webapp.webapps[0].id }}" 
