
#  vars:
#    resource_group: base-rg
#   location: eastus 
#   vnet_name: base-vnet 
#   subnet_name: base-subnet 
#    publicip_name: base-publicip
#    publicip_domain: base-domain
#  tasks:
    - name: Create a virtual network "{{ vnet_name }}"
      azure_rm_virtualnetwork:
        name: "{{ vnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefixes_cidr:
            - 10.1.0.0/16
            - 172.100.0.0/16
        dns_servers:
            - 127.0.0.1
            - 127.0.0.2

    - name: Create a subnet "{{ subnet_name }}"
      azure_rm_subnet:
        name: "{{ subnet_name }}"
        virtual_network_name: "{{ vnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefix_cidr: 10.1.0.0/24

    - name: Create a public IP address "{{ publicip_name }}"
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}" 
        allocation_method: Static
        sku: standard
        name: "{{ publicip_name }}"
        domain_name_label: "{{ publicip_domain }}"
