resource_group: image-rg
location: eastus
virtual_network_name: image-vnet
subnet_name: image-subnet
ip_name: image-ip
source_vm_name: vm-for-images
network_interface_name: image-nic
image_name: test-image
shared_gallery_name: image_Gallery
shared_image_name: myImage
shared_image_version: 10.1.3
vm_name: testvm001
vmss_name: testvmssx
snapshot_name: mySnapshot
vmss_ip: vmssip
