- hosts: localhost
  vars_files:
    - ./vars.yml

  tasks:

    - name: Subnet for App Gateway
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}appgw"
        address_prefix: "10.0.2.0/24"
        virtual_network: "{{ virtual_network_name }}"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ vmss_name }}pipgw"
        sku: Standard


    - name: Create instance of Application Gateway "{{ appgw_name }}"
      azure_rm_appgateway:
        resource_group: "{{ resource_group }}"
        name:  appgw_name
        sku:
          name: standard_v2
          tier: standard_v2
          capacity: 2
        gateway_ip_configurations:
          - subnet:
              name: "{{ subnet_name }}appgw"
              virtual_network_name: "{{ virtual_network_name }}"
            name: appGatewayIP
        frontend_ip_configurations:
          - name: appGatewayFrontendIP
            public_ip_address:  "{{ vmss_name }}pipgw"
        frontend_ports:
          - port: 80
            name: appGatewayFrontendPort
        backend_address_pools:
          - backend_addresses:
            name: appGatewayBackendPool
        backend_http_settings_collection:
          - port: 80
            protocol: http
            cookie_based_affinity: enabled
            name: appGatewayBackendHttpSettings
        http_listeners:
          - frontend_ip_configuration: appGatewayFrontendIP
            frontend_port: appGatewayFrontendPort
            name: appGatewayHttpListener
        request_routing_rules:
          - rule_type: basic
            backend_address_pool: appGatewayBackendPool
            backend_http_settings: appGatewayBackendHttpSettings
            http_listener: appGatewayHttpListener
            name: rule1



    - name: Create VMSS
      azure_rm_virtualmachinescaleset:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        virtual_network_name: "{{ virtual_network_name }}"
        subnet_name:  "{{ subnet_name }}"
        security_group_name: "{{ source_vm_name }}nsg"
        public_ip_per_vm: true
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        admin_password: Password@123
        ssh_password_enabled: true
        capacity: 2
        tier: Standard
        managed_disk_type: Standard_LRS
        os_disk_caching: ReadWrite
        application_gateway: appgw_name
        image:
          id: "/subscriptions/94ed9036-68b2-45bc-ad88-b18cfd0827b5/resourceGroups/image-rg/providers/Microsoft.Compute/galleries/image_Gallery/images/myImage/versions/10.1.3"


