- hosts: localhost
  connection: local
  vars_files:
    - ./vars.yml

  tasks:
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ vmss_name }}publicip"
        sku: Standard
    - name: Create a load balancer
      azure_rm_loadbalancer:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}lb"
        location: "{{ location }}"
        sku: Standard
        frontend_ip_configurations:
          - name: "{{ vmss_name }}front-config"
            public_ip_address: "{{ vmss_name }}publicip"
        backend_address_pools:
          - name: "{{ vmss_name }}backend-pool"
        probes:
          - name: "{{ vmss_name }}prob0"
            protocol: Tcp
            port: 80
            interval: 10
            fail_count: 3
              #inbound_nat_rules:
              #- name: "{{ vmss_name }}nat-pool"
              #frontend_ip_configuration: "{{ vmss_name }}front-config"
              #protocol: Tcp
              #frontend_port: 50000
              #frontend_port_range_end: 50040
              #backend_port: 22
        load_balancing_rules:
          - name: "{{ vmss_name }}lb-rules"
            frontend_ip_configuration: "{{ vmss_name }}front-config"
            backend_address_pool: "{{ vmss_name }}backend-pool"
            frontend_port: 80
            backend_port: 80
            protocol: Tcp
            probe: "{{ vmss_name }}prob0"

    - name: Create a virtual machine scale set using a shared image
      azure_rm_virtualmachinescaleset:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        security_group_name: "{{ source_vm_name }}nsg"
          #public_ip_per_vm: true
        vm_size: Standard_DS1_v2
        admin_username: adminUser
        admin_password: PassWord01
        ssh_password_enabled: true
        capacity: 5
        virtual_network_name: "{{ virtual_network_name }}"
        subnet_name: "{{ subnet_name }}"
        tier: Standard
        managed_disk_type: Standard_LRS
        os_disk_caching: ReadWrite
        load_balancer: testvmssxlb
        image:
          id: "/subscriptions/94ed9036-68b2-45bc-ad88-b18cfd0827b5/resourceGroups/image-rg/providers/Microsoft.Compute/galleries/image_Gallery/images/myImage/versions/10.1.3"
        data_disks:
          - lun: 0
            disk_size_gb: 20
            managed_disk_type: Standard_LRS
            caching: ReadOnly
           
